Power-Response.ps1
=> Add Comments

Power-Response.ps1
Fixes #4 - Remove Optional Input
=> Remove Optional Input

Power-Response.ps1
Removed `Description` parameter and matching logic
=> Removed description

Power-Response.ps1
=> 3 back functionality

Config.example.psd1, Power-Response.ps1
=> 6 admin credentials

Config.example.psd1, Power-Response.ps1
=> 12 hide items

Power-Response.ps1
=> Added parameter functionality

.gitignore, Create-DirectoryStructure.ps1
Added a script to generate a random set of files and directories.
I can go back through it later and comment everything if people are interested, but since this is tangential to the actual project I didn't bother for the first round.
=> Added test directory structure script

Create-DirectoryStructure.ps1, Power-Response.ps1
=> 28 execute script files

Power-Response.ps1
=> Added banner for Power-Response

Power-Response.ps1
#33  - resolves issues if users run from explorer by using 'run with PowerShell option'
=> Added better handling around initial run errors

Power-Response.ps1
- (Invoke-RunCommand) Fixed single parameter passed type issue (nonsplattable DictionaryEntry vs splattable Hashtable)
- (Invoke-SetCommand) Fixed blank set value to remove the parameter from the tracked list
- (Invoke-RemoveCommand) Added 'remove' keyword to remove parameters from the tracked list
=> Fixed Parameter Quirks

Power-Response.ps1
(Invoke-RunCommand) fixed parameter passing when executing selected script files
=> Fixed parameter passing

Power-Response.ps1
Alphabetized functions
Fixed remove aliases (`rm`, `del` -> `clear`)
Renamed `Invoke-PowerCommand` to `Invoke-PRCommand`
=> Format fixes

Config.example.psd1, Power-Response.ps1
Added Out-PRFile function for handling script output
- Exports whatever object is handed it to a CLIXML file
- Output file naming convention: `plugin basename`_`utc timestamp`.xml
- Makes the file ReadOnly after export
- Hashes the file for integrity checking and stores it in an output hashes CSV
=> Add Out-PRfile

Power-Response.ps1
Fixed the pipeline support for Out-PRFile
=> Fixed Out-PRFile Pipeline Support

Power-Response.ps1
Added CSV output to Out-PRFile
Also added error handling to data exports and consolidated `Set-ItemProperty` and `Get-FileHash` calls
=> Added CSV output to Out-PRFile

Config.example.psd1, Power-Response.ps1
Implemented Write-Log function (CSV format currently)
Item tracked in log:
- Date
- UserName
- Context (generic `Menu` or specific `Plugin\Path`)
- Message
Logging actions implemented:
- Starting up Power-Response framework
- Setting a parameter
- Removing a parameter
- Parameter format issue
- Executing plugin
- Execution success/error of plugin
- Output generated through `Out-PRFile` including path and file hash
=> Implemented Write-Log

Power-Response.ps1
Fixed the output file timestamp to be 24 hours
=> 24 hr timestamp

Power-Response.ps1
fixes #52 
added status message
=> Added status message for plugin execution

Power-Response.ps1
Added milliseconds to output file names
Fixes #58
=> Added milliseconds

Power-Response.ps1
=> Fixed string parameter formatting

Plugins/Import-Computers.ps1
=> Import-Computers.ps1 Plugin

Power-Response.ps1
=> added clear screen functionality

Power-Response.ps1
=> added empty parameter message

Power-Response.ps1
=> added cls alias for clear and fixed help menu for directories

Power-Response.ps1
=> Plugin validation and error message clean up

Extras/Config.example.psd1, Extras/Create-DirectoryStructure.ps1
Cleaned up root dir by moving unnecessary files to the Extras directory
=> cleaned up root directory

Power-Response.ps1
Added global access handling for the following attributes:
- Config
- Location
- Parameters
=> Global Access

Power-Response.ps1
Fixed output to allow for plugin specified directories along with ComputerName subdirectory organization
Also tracked a global variable `$global:PowerResponse.OutputPath` for plugins to direct files copied back
=> Revamped Output

Power-Response.ps1
fixes #145 
Additionally, fixes user feedback from Power-Response console during plugin execution as it iterates through each $Computer object (recent updates caused undesired changes).
=> Fixed feedback for users

Power-Response.ps1
=> Changed Author Names

Power-Response.ps1
Fixed a Plugin directory traversal up to the main Power-Response directory.
=> Plugin Root Run Command Directory Traversal

Plugins/Process/Collect-Processes.ps1, Plugins/Process/Collect-WMI_Processes.ps1
Process collection using WMI for remote hosts.
=> Collect-WMI_Processes.ps1

Plugins/ASEP/Collect-ASEP.ps1, Plugins/ASEP/Collect-SigCheck.ps1
fixes ASEP and sigcheck output issues
=> fixes output issues

Plugins/Logs/Collect-PSReadLine.ps1
=> Collect-PSReadLine.ps1

Plugins/Network/Collect-NetworkData.ps1
=> Added ARP and fixed Get-NetRoute

Plugins/Process/Collect-Prefetch.ps1
=> Collect-Prefetch.ps1

Plugins/Configuration/Collect-SystemInfo.ps1
Collects system information on remote hosts. Assists with building host profiles.
=> Collect-SystemInfo.ps1

Plugins/Process/Collect-PrefetchListing.ps1
Retrieves a listing of Prefetch directory contents without having to pull back all prefetch files
=> Collect-PrefetchListing.ps1

Plugins/Logs/Collect-WindowsEvents.ps1, Plugins/Logs/Collect-WindowsEventsDetailed.ps1
Fixes performance issues with Collect-WindowsEvents and Adds a new plugin for Collect-WindowsEventsDetailed.
=> Windows Event Log Fixes

Plugins/Configuration/Collect-ScheduledTaskInfo.ps1, Plugins/Configuration/Collect-ScheduledTasks.ps1, Plugins/Process/Collect-Prefetch.ps1
fixes #120 
1) Plugin to get list of scheduled tasks
2) Plugin to retrieve scheduled task configuration files
3) Additional functionality added to Collect-Prefetch.ps1 to add ability to specify specific pf file (inspired from collect-scheduledtasks.ps1)
=> Scheduled tasks plugins and prefetch plugin fix

Plugins/Memory/Collect-MemoryWinpmem.ps1
=> Collect-MemoryWinpmem.ps1

Plugins/Memory/Collect-MemoryWinpmem.ps1, Plugins/SysInternals/Collect-SigCheck.ps1
Fixes bin path on autoruns and sigcheck plugins
=> Autoruns fix

Plugins/Configuration/Collect-ScheduledTasks.ps1, Plugins/Memory/Collect-MemoryWinpmem.ps1, Plugins/Process/Collect-Prefetch.ps1
Cleaned up profile creation through PS remoting. added option for no profile creation.
=> added option to not have a profile created with PS remoting

Plugins/Disk/Collect-MFT.ps1, Plugins/Triage/Collect-WindowsArtifacts.ps1
=> Issue #196

Plugins/Disk/Collect-Amcache.ps1, Plugins/Disk/Collect-MFT.ps1, Plugins/Triage/Collect-WindowsArtifacts.ps1
=> Issue #107

Plugins/ProgramExecution/Collect-UserAssist.ps1
=> UserAssist Plugin

Plugins/ProgramExecution/Collect-Jumplists.ps1, Plugins/ProgramExecution/Collect-Prefetch.ps1
=> Jumplists, userassist, prefetch

Plugins/Persistence/Collect-RunKeys.ps1
=> Run keys plugin

Power-Response.ps1
Fixes #217 
Added date subfolder to OutputPath
=> Fixed Output Path

Plugins/Analysis/Analyze-Prefetch.ps1, Plugins/ProgramExecution/Collect-Prefetch.ps1
1st analysis plugin. whoo hoo.
=> Analysis plugin for prefetch collection

Plugins/ProgramExecution/Collect-Prefetch.ps1
=> fixes .pf files collection and skips non prefetch files

Plugins/Persistence/Collect-RunKeys.ps1, Plugins/ProgramExecution/Collect-Prefetch.ps1
=> Fixing da runkeys

Plugins/Analysis/Analyze-Prefetch.ps1, Plugins/Analysis/Analyze-RecentFiles.ps1
=> parentheses are fun

Plugins/Execution/Collect-Handles.ps1
=> Collect-Handles.ps1

Power-Response.ps1
Added a pre-execution filter to find online computers and print out message when some are offline.
Also normalized tracked ComputerName s to uppercase for consistent formatting
=> Online Computer

Config.example.psd1, Plugins/Execution/Collect-Processes.ps1, Plugins/Import-Computers.ps1, Power-Response.ps1
Full PSRemoting integration to the framework for any plugins that do not request a `Session` parameter.
Will Fix #204
=> PSRemoting

Plugins/Network/Collect-ArpCache.ps1, Plugins/Network/Collect-DNSCache.ps1, Plugins/Network/Collect-InterfaceDetails.ps1, Plugins/Network/Collect-NetworkConnections.ps1, Plugins/Network/Collect-NetworkProfiles.ps1, Plugins/Network/Collect-NetworkRoutes.ps1, Plugins/Network/Collect-SessionDrives.ps1
Network plugins conversion to new format
=> plugin-conversion1

Plugins/Persistence/Collect-StartupDirListing.ps1
=> collect-startupdirlisting.ps1

Plugins/Disk/Retrieve-Items.ps1, Plugins/Disk/Retrieve-MFT.ps1, Plugins/Disk/Retrieve-RegistryHives.ps1, Plugins/Execution/Retrieve-Amcache.ps1, Plugins/Execution/Retrieve-Jumplists.ps1, Plugins/Execution/Retrieve-ShimCache.ps1, Plugins/Logs/Retrieve-EventLogFiles.ps1, Plugins/Logs/Retrieve-SRUMDB.ps1, Plugins/Memory/Retrieve-MemoryWinpmem.ps1, Plugins/Network/Retrieve-BrowsingHistory.ps1, Plugins/Triage/Retrieve-WindowsArtifacts.ps1
Renamed `Get-PROutputPath` to `Get-PRPath`
=> Renamed Get-PROutputPath to Get-PRPath

Plugins/Disk/Retrieve-NTFSArtifacts.ps1, Plugins/Disk/Retrieve-RecycleBin.ps1, Plugins/Triage/Retrieve-WindowsArtifacts.ps1
Created plugin to retrieve $Recycle.Bin contents
Converted retrieve-MFT.ps1 to retrieve-NTFSArtifacts.ps1 which collects $Extend\$UsnJrnl:$J, $LogFile, $Boot, and $Secure:$SDS in addition to $MFT. 
Also updated Retrieve-WindowsArtifacts.ps1 to retrieve these as well.
=> Added recycle bin plugin and enhanced NTFS artifacts

Plugins/Analysis/Analyze-Amcache.ps1, Plugins/Analysis/Analyze-Jumplists.ps1, Plugins/Analysis/Analyze-NTFSArtifacts.ps1, Plugins/Analysis/Analyze-Prefetch.ps1, Plugins/Analysis/Analyze-RecentItems.ps1, Plugins/Analysis/Analyze-RecycleBin.ps1, Plugins/Analysis/Analyze-RegistryHives.ps1, Plugins/Analysis/Analyze-ShimCache.ps1, Plugins/Disk/Retrieve-Items.ps1, Plugins/Disk/Retrieve-NTFSArtifacts.ps1, Plugins/Disk/Retrieve-RecycleBin.ps1, Plugins/Disk/Retrieve-RegistryHives.ps1, Plugins/Execution/Retrieve-Amcache.ps1, Plugins/Execution/Retrieve-Jumplists.ps1, Plugins/Execution/Retrieve-Prefetch.ps1, Plugins/Execution/Retrieve-ShimCache.ps1, Plugins/Execution/Retrieve-SigCheck.ps1, Plugins/Logs/Retrieve-EventLogFiles.ps1, Plugins/Logs/Retrieve-SRUMDB.ps1, Plugins/Memory/Retrieve-MemoryWinpmem.ps1, Plugins/Network/Retrieve-BrowsingHistory.ps1, Plugins/Persistence/Retrieve-AutoRuns.ps1, Plugins/Triage/Retrieve-WindowsArtifacts.ps1
=> Fixed execution strings for paths that will contain spaces

Power-Response.ps1
* Remove machine online check
* Fixed Config `$false` value bug
* Trimmed `$UserInput` as it is accepted so space splitting functions as intended
Fixes #289
=> Removed Ping Sweep

Plugins/Analysis/Analyze-Amcache.ps1, Plugins/Analysis/Analyze-Jumplists.ps1, Plugins/Analysis/Analyze-NTFSArtifacts.ps1, Plugins/Analysis/Analyze-RecycleBin.ps1, Plugins/Analysis/Analyze-RegistryHives.ps1, Plugins/Analysis/Analyze-ShimCache.ps1, Plugins/Disk/Retrieve-Items.ps1, Plugins/Execution/Retrieve-Jumplists.ps1, Plugins/Execution/Retrieve-RecentItems.ps1, Power-Response.ps1
=> Comment Fix

Power-Response.ps1
Reverts Asymmetric-InfoSec/Power-Response#307
=> Revert "Fixed Path Generation"

Power-Response.ps1
Fixed the path initialization of the Power-Response config directories.
=> Fixed Path Initialization

Power-Response.ps1
=> Fixed error handling for invoke-runcommand

Power-Response.ps1
=> comment removal

Power-Response.ps1
Fixed the output path for plugins called from within triage plugins.
Also added the plugin name to print messages for clarity when executing triage plugins
=> Fixed Output Path for Triage Plugins

Plugins/Disk/Retrieve-FLSBody.ps1
=> FLS body plugin

README.md, Setup.ps1
Changed `Config-PR` to `Setup` and resolved README references.
=> Changed Config-PR to Setup

Config.example.psd1, Power-Response.ps1, Setup.ps1
- Added handling for the configuration option `OutputType` of `XLSX` to add content to an Excel file for easy viewing
- Added configuration option `ExcelName` with a default value of `power-response.xlsx` for the name of the excel document at the root of a machine's output folder
=> Consolidate Output

Plugins/Hunt/Hunt-Processes.ps1, Plugins/Triage/Triage-Execution.ps1, Power-Response.ps1
- Modified Session handling to improve performance
- Added parameter `HuntName` to `Invoke-PRPlugin` to enable data aggregation for threat hunting
- Added example Hunt plugin skeleton `Hunt-Processes`
=> Added Hunt Capability

Plugins/Disk/Retrieve-FLSBody.ps1
=> fls output fix

Plugins/Persistence/Collect-ScheduledTaskDetails.ps1
=> fixed extra curly brace

Power-Response.ps1
=> typo fixes for missing

Plugins/Disk/Retrieve-Items.ps1, Plugins/Disk/Retrieve-NTFSArtifacts.ps1, Power-Response.ps1
Removed Velociraptor references from Retrieve-NTFSArtifacts.
Also fixed a mispelling in Power-Response.
=> Refactored Retrieve-NTFSArtifacts to remove Velociraptor

Plugins/Disk/Retrieve-RecycleBin.ps1
Removed Velociraptor references from Retrieve-RecycleBin.
Am running into a weird Copy-PRItem error `Copy-PRItem : Invoke command error: A parameter cannot be found that matches parameter name 'Raw'.`
=> Removed Velociraptor from Retrieve-RecycleBin

Plugins/Disk/Retrieve-RegistryHives.ps1
Removed Velociraptor from Retrieve-RegistryHives in favor of `Copy-PRItem`.
=> Removed Velociraptor from Retrieve-RegistryHives

Plugins/Disk/Retrieve-RegistryHives.ps1
Fixed some path issues with the registry hives.
=> Fix Retrieve-RegistryHives

Power-Response.ps1
Fixed remote file hash mismatch in Copy-PRItem
=> Fixed Copy-PRItem

Plugins/Eradicate/Eradicate-Files.ps1, Power-Response.ps1
Added `Write-PRHost`, `Write-PRError`, and `Write-PRWarning` functions to write to the specific stream, and also log the message in the Power-Response log.
=> Added Write Functions

Power-Response.ps1
Improved the core menu logic to better support global use of `back` command.
=> Improved Master Logic

Power-Response.ps1
I brokeded it. Then I fixeded it.
=> Fixed Master Logic

Config.example.psd1, Power-Response.ps1
Added RemoteStagePath option to the Config file.
=> Added RemoteStagePath

Config.example.psd1, Power-Response.ps1
Added Config item to set the ZIP Encryption Password
=> Config EncryptPassword

Power-Response.ps1
Added a plugin execution log for each host under investigation.
=> Added Plugin Log

Power-Response.ps1
Created and fixed the host plugin log.
=> Plugin Log

Power-Response.ps1
=> Fixed Git Garbage

Power-Response.ps1
=> Plugin Log UTC

Plugins/Analysis/Analyze-NTFSArtifacts.ps1, Plugins/Disk/Retrieve-Items.ps1, Plugins/Disk/Retrieve-NTFSArtifacts.ps1, Power-Response.ps1
Refactored Retrieve-NTFSArtifacts and Analyze-NTFSArtifacts
=> Fixed Retrieve-NTFSArtifacts

Plugins/Disk/Retrieve-Items.ps1, Plugins/Disk/Retrieve-NTFSArtifacts.ps1, Plugins/Disk/Retrieve-RecycleBin.ps1, Plugins/Disk/Retrieve-RegistryHives.ps1, Plugins/Execution/Retrieve-Amcache.ps1, Plugins/Execution/Retrieve-Handles.ps1, Plugins/Execution/Retrieve-Jumplists.ps1, Plugins/Execution/Retrieve-Prefetch.ps1, Plugins/Execution/Retrieve-RecentItems.ps1, Plugins/Execution/Retrieve-WindowsSearchData.ps1, Plugins/Logs/Retrieve-EventLogFiles.ps1, Plugins/Logs/Retrieve-PSReadLine.ps1, Plugins/Logs/Retrieve-SRUMDB.ps1, Plugins/Network/Retrieve-BrowsingHistory.ps1, Plugins/Network/Retrieve-HostsFile.ps1, Plugins/Persistence/Retrieve-ScheduledTasks.ps1, Plugins/Persistence/Retrieve-Startup.ps1, Power-Response.ps1
Fixed errors related to dependency discovery across all retrieve plugins.
=> Fixed Dependency Discovery Errors

Plugins/Triage/Triage-Execution.ps1, Plugins/Triage/Triage-Network.ps1, Plugins/Triage/Triage-Persistence.ps1
Refactored all triage plugins except `Triage-WindowsArtifacts`
=> Refactored Triage Plugins

Plugins/Disk/Retrieve-FLSBody.ps1, Plugins/Disk/Retrieve-NTFSArtifacts.ps1, Plugins/Disk/Retrieve-RecycleBin.ps1, Plugins/Disk/Retrieve-RegistryHives.ps1, Plugins/Disk/Retrieve-Shellbags.ps1, Plugins/Execution/Collect-UserAssist.ps1, Plugins/Execution/Retrieve-Amcache.ps1, Plugins/Execution/Retrieve-Jumplists.ps1, Plugins/Execution/Retrieve-Prefetch.ps1, Plugins/Execution/Retrieve-RecentItems.ps1, Plugins/Execution/Retrieve-ShimCache.ps1, Plugins/Execution/Retrieve-SigCheck.ps1, Plugins/Execution/Retrieve-WindowsSearchData.ps1, Plugins/Logs/Retrieve-EventLogFiles.ps1, Plugins/Logs/Retrieve-PSReadLine.ps1, Plugins/Logs/Retrieve-SRUMDB.ps1, Plugins/Memory/Retrieve-MemoryWinpmem.ps1, Plugins/Network/Retrieve-BrowsingHistory.ps1, Plugins/Network/Retrieve-HostsFile.ps1, Plugins/Persistence/Retrieve-AutoRuns.ps1, Plugins/Persistence/Retrieve-ScheduledTasks.ps1, Plugins/Persistence/Retrieve-Startup.ps1
=> Force update

Power-Response.ps1
Retain timestamps on files copied with `Copy-PRItem`
=> Copy-PRItem Carries Timestamps

Power-Response.ps1
Fixes #440 
Add WarningAction of SilentlyContinue to the export XLSX AutoSize call.
=> Suppress Excel AutoSize Warning

Plugins/Triage/Triage-Persistence.ps1, Power-Response.ps1
Fixed Collect-RunKeys reference to Collect-RegKeyPersistence in Triage-Persistence.
=> Fixed Collect-RunKeys Reference

Power-Response.ps1
=> Added plugin help to invoke-helpcommand

Plugins/Triage/Triage-Persistence.ps1, Power-Response.ps1
Treat parameters of type SwitchParameter like Booleans for more sensible casting.
=> Cast Switch Parameters to Boolean Values

Plugins/Triage/Triage-Persistence.ps1, Power-Response.ps1
Display default parameter values.
Fixes #464
=> Display Default Values for Parameters

Power-Response.ps1
Added added `Parameter` parameter.
Useful for running plugins from the command line that require additional parameters such as `Retrieve-Items` using `Path`.
=> Added Parameter Parameter

Power-Response.ps1
Improved framework log message capability.
Explicitly short-circuit running any plugin with no successful sessions.
=> Framework Logging Improvements
